server:
  port: 8002
hello:
  message: "Service One"

spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "website3_root"
    password: "khoa123456@"
    url: "jdbc:mysql://103.200.23.98:3306/website3_database-test?createDatabaseIfNotExist=false"